import type { StrategyData } from "./types";

export const DATA: StrategyData = {
	F1: {
		dim: 2,
		desc: "Contamination detection — 0 is optimal (avoid sources)",
		allBest: { value: "2.68e-09", week: "W6" },
		weeks: [
			{
				w: "Initial",
				strategy: "GP-UCB uniform",
				beta: null,
				result: "0.0",
				trend: "new",
				change: "new",
				what: "GP-UCB (Gaussian Process Upper Confidence Bound) fitted a GP surrogate to the initial data, then maximised μ + β·σ across 10,000 random candidates — balancing mean prediction with uncertainty. The same β was applied to all 8 functions with no per-function tuning.",
				why: "With no query history yet, there was no basis for function-specific decisions. A uniform GP-UCB pass across all functions was the only sensible starting point. The initial output was 0.0, which in retrospect turned out to be the global optimum — but that wasn't yet known.",
			},
			{
				w: "W1–W2",
				strategy: "GP-UCB uniform",
				beta: "~2.0",
				result: "≈0",
				trend: "flat",
				change: "same",
				what: "Continued the same uniform GP-UCB approach as Initial, with β≈2.0 across all functions. GP fitted on growing history, candidates sampled uniformly at random.",
				why: "Both weeks returned values near zero. At this point the function appeared completely flat — every probe gave the same output. Two data points weren't enough to diagnose the real issue, and the natural assumption was that the GP's uncertainty was leading us to uninteresting regions.",
			},
			{
				w: "W3",
				strategy: "GP-UCB aggressive",
				beta: "2.5",
				result: "≈0",
				trend: "flat",
				change: "pivot",
				what: "GP-UCB with β raised to 2.5. A higher β amplifies the σ (uncertainty) term, causing the acquisition function to strongly prefer points where the GP is most uncertain — driving the algorithm into unexplored corners of the space rather than refining already-visited regions.",
				why: "After three consecutive ≈0 results, the hypothesis was that GP's default exploration wasn't covering enough of the 2D space. Raising β was a direct attempt to force exploration into regions the GP was avoiding. The result was still ≈0 — suggesting this wasn't an exploration-depth problem but something structural about the function itself.",
			},
			{
				w: "W4",
				strategy: "Manual corner probe",
				beta: null,
				result: "≈0",
				trend: "flat",
				change: "pivot",
				what: "GP-UCB was abandoned entirely in favour of deterministic manual queries. The function description mentions 'contamination sources' where only proximity yields a non-zero reading — and crucially the output is zero elsewhere, meaning zero IS the safe (optimal) state. The four corners of the 2D unit cube were probed one at a time, starting with [0.05, 0.05].",
				why: "The key insight was re-reading the problem description: a contamination detector returns 0 when far from sources, and non-zero (bad) when near them. This means 0 IS the maximum we want — not a sign of failure. GP-UCB was actively searching for peaks that don't exist as 'improvements'. Manual corner probing was chosen to systematically confirm 0.0 as the true optimum by ruling out whether any corner hides a contamination source.",
			},
			{
				w: "W5",
				strategy: "Manual corner probe",
				beta: null,
				result: "≈0",
				trend: "flat",
				change: "same",
				what: "Second corner: [0.95, 0.05]. Same logic as W4 — systematic manual coverage of the 4 extreme corners of the domain.",
				why: "The corner [0.05, 0.05] returned ≈0, confirming no contamination source in the lower-left. The strategy was to work through the remaining corners before drawing conclusions. Two of four corners confirmed clean.",
			},
			{
				w: "W6",
				strategy: "Manual center probe",
				beta: null,
				result: "2.68e-09",
				trend: "new",
				change: "pivot",
				what: "Rather than a corner, the center of the domain [0.50, 0.50] was probed — the point maximally equidistant from all four edges, and therefore least likely to be near a boundary contamination source.",
				why: "Two corners had been confirmed flat. Before finishing all four corners, it was worth checking whether any interior peak existed. The center returned 2.68e-09 — effectively still zero but the largest non-zero value seen. This became the all-time best by default, confirming the function is essentially flat everywhere and 0 (or ≈0) is genuinely the optimum.",
			},
			{
				w: "W7",
				strategy: "Manual corner probe",
				beta: null,
				result: "≈0",
				trend: "flat",
				change: "pivot",
				what: "Resumed corner probing: [0.05, 0.95]. Third corner in the systematic sweep.",
				why: "The center probe didn't reveal a meaningful peak. Systematic corner coverage was resumed to complete the landscape audit. Three of four corners now confirmed at ≈0.",
			},
			{
				w: "W8",
				strategy: "Manual corner probe",
				beta: null,
				result: "≈0",
				trend: "flat",
				change: "same",
				what: "Final corner: [0.95, 0.95]. Completing the 4-corner plus center coverage of the 2D domain.",
				why: "All four corners and the center have now returned ≈0 — exhaustive coverage of the five canonical reference points in a 2D unit square. With no evidence of any non-zero region, 0.0 is accepted as the global optimum. No further manual probing is justified.",
			},
			{
				w: "W9",
				strategy: "GP-UCB",
				beta: "1.5",
				result: "≈0",
				trend: "flat",
				change: "pivot",
				what: "Returned to GP-UCB (β=1.5) now that the manual sweep was complete. The GP was fitted on all accumulated data and allowed to select the next query freely.",
				why: "Manual probing had exhausted the obvious reference points. GP-UCB was re-introduced to let the surrogate explore any uncovered regions. The result was ≈0 again, fully confirming the conclusion that this function is flat everywhere in the feasible domain.",
			},
			{
				w: "W10",
				strategy: "GP Gradient Ascent",
				beta: null,
				result: "≈0",
				trend: "flat",
				change: "pivot",
				what: "GP Gradient Ascent fits the GP surrogate and then computes ∂(μ + β·σ)/∂x, stepping in the direction of steepest increase on the acquisition surface. This is more directed than random candidate sampling, theoretically reaching acquisition function peaks more precisely.",
				why: "Tried as a last resort to find any non-trivial structure. On a flat function like F1, gradient ascent finds near-zero gradient everywhere, so the algorithm takes effectively arbitrary steps. The result was ≈0 as expected — confirming there is no gradient to follow.",
			},
			{
				w: "W11",
				strategy: "GradientBoosting (log-scaled)",
				beta: null,
				result: "-3.24e-05",
				trend: "reg",
				change: "pivot",
				what: "GradientBoosting Regressor used as the surrogate model instead of a GP. Because F1 outputs are near-zero floating point values (e.g. 2.68e-09), a log₁₀ transform was applied first to make differences between tiny values distinguishable. The GradientBoosting model was fitted on log-scaled outputs and its predicted maximum used as the query.",
				why: "The log transform idea was sound — without it, GradientBoosting treats 2.68e-09 and 1.69e-88 as essentially identical. However the query it proposed ([0.65, 0.55]) moved toward a region with a contamination source, returning -3.24e-05 — the first negative value seen. The model over-fit to tiny positive variations and was steered toward a bad region.",
			},
			{
				w: "W12",
				strategy: "GP-UCB β=3.0 (log-scaled)",
				beta: "3.0",
				result: "1.69e-119",
				trend: "reg",
				change: "pivot",
				what: "GP-UCB with maximum exploration (β=3.0) on log-scaled outputs. At β=3.0, the acquisition function is almost entirely driven by σ — uncertainty — rather than the GP mean. This is essentially 'go wherever we know the least', maximising coverage over exploitation.",
				why: "With F1 far behind the classmate benchmark (who reportedly found a peak via 'diagonal discovery'), maximum aggression was the only remaining option. β=3.0 forced the GP into completely unvisited areas. The result (1.69e-119) is astronomically small — effectively zero — and a regression from W6's best. No useful peak was found.",
			},
		],
	},

	F2: {
		dim: 2,
		desc: "Noisy function, many local optima — GradientBoosting broke 10-week plateau",
		allBest: { value: "0.6966", week: "W12" },
		weeks: [
			{
				w: "Initial",
				strategy: "GP-UCB uniform",
				beta: null,
				result: "0.611",
				trend: "new",
				change: "new",
				what: "Standard GP-UCB on the initial dataset. The initial outputs happened to include a strong reading of 0.611, making this the baseline to beat.",
				why: "No prior history. The initial data serendipitously placed a strong result at 0.611, which would prove incredibly persistent — lasting as the best result for 10 consecutive weeks despite dozens of attempts to improve on it.",
			},
			{
				w: "W1",
				strategy: "GP-UCB uniform",
				beta: "~2.0",
				result: "0.337",
				trend: "reg",
				change: "same",
				what: "GP-UCB β≈2.0, uniform candidate sampling across the domain.",
				why: "The GP was still learning the landscape from only a handful of points. With β=2.0, uncertainty drove the query away from the 0.611 region into an area returning only 0.337. The noisy, multi-modal nature of F2 means the GP's smooth RBF surface is a poor approximation of the true function at this early stage.",
			},
			{
				w: "W2",
				strategy: "GP-UCB uniform",
				beta: "~2.0",
				result: "0.592",
				trend: "new",
				change: "same",
				what: "GP-UCB β≈2.0, uniform sampling. The GP now had one more data point near the 0.337 region and adjusted its surface accordingly.",
				why: "The GP's updated model directed a candidate back closer to the 0.611 basin, recovering to 0.592. This wasn't the result of a strategic change — the GP naturally triangulated between data points. Proximity to 0.611 was encouraging but still short of the initial best.",
			},
			{
				w: "W3",
				strategy: "GP-UCB exploitation",
				beta: "1.0",
				result: "-0.052",
				trend: "reg",
				change: "pivot",
				what: "β dropped sharply to 1.0, shifting the acquisition function toward pure exploitation of the GP mean. With lower uncertainty weight, the algorithm focuses on regions the GP predicts to be high-value based on observed data, rather than exploring new territory.",
				why: "With 0.592 in W2 and 0.611 in initial data both near the same region, it looked like the function had a clear basin worth exploiting. Dropping β to 1.0 was intended to commit to that basin. Instead, the query landed at -0.052 — a badly negative value. F2's many local optima mean there are sharp valleys adjacent to peaks, and the GP's smooth mean led directly into one.",
			},
			{
				w: "W4",
				strategy: "GP-UCB exploration",
				beta: "2.0",
				result: "0.587",
				trend: "new",
				change: "pivot",
				what: "β raised back to 2.0 and a bias fraction of 0.3 introduced — meaning 30% of candidates were sampled near the best-known point rather than uniformly at random. This hybrid approach maintains exploration pressure while slightly anchoring the search near known good regions.",
				why: "W3's -0.052 was a clear signal: pure exploitation on a noisy multi-modal function is dangerous. The GP's mean over a landscape with many local optima is unreliable as a guide. Raising β back to 2.0 restored exploration pressure. The bias fraction gave a gentle nudge toward the 0.611 region without fully committing. Result: 0.587 — nearly recovering to the initial best.",
			},
			{
				w: "W5",
				strategy: "GP-UCB moderate",
				beta: "1.5",
				result: "0.187",
				trend: "reg",
				change: "pivot",
				what: "β reduced to 1.5 (between exploitative 1.0 and explorative 2.0) with bias fraction 0.4. The intent was to incrementally shift toward exploitation of the 0.587/0.611 basin while still allowing the GP some exploration freedom.",
				why: "W4's recovery to 0.587 made it tempting to nudge β downward. However this was a classic mistake: over-reacting to a single successful round. β=1.5 with bias=0.4 hit another local minimum at 0.187. On a function with many local optima, even moderate β reduction can cause the GP to steer into a valley. This reinforced the theoretical caution around early exploitation in multi-modal landscapes.",
			},
			{
				w: "W6",
				strategy: "GP-UCB exploit",
				beta: "1.0",
				result: "0.529",
				trend: "new",
				change: "pivot",
				what: "β dropped back to 1.0 but bias fraction raised to 0.5 — half of all candidates now sampled within a tight Gaussian around the current best point. This is aggressive exploitation: uncertainty largely discounted, search heavily anchored near the best-known location.",
				why: "W5's 0.187 was attributed to the GP straying too far from the 0.611 region. Increasing the bias fraction to 0.5 forced candidates to cluster tightly enough around the good region that even a noisy landscape couldn't steer the query too far astray. Recovery to 0.529 validated the approach, though still short of 0.611.",
			},
			{
				w: "W7",
				strategy: "GP-UCB + Matern kernel",
				beta: "1.5",
				result: "0.442",
				trend: "reg",
				change: "pivot",
				what: "The RBF kernel was replaced with the Matérn 5/2 kernel. RBF assumes infinite differentiability and produces very smooth GP surfaces. Matérn 5/2 allows for rougher, less smooth functions and is generally better suited to real-world functions that aren't infinitely differentiable. β was also raised back to 1.5.",
				why: "F2 is noisy with many local optima — precisely the kind of rough landscape where RBF's smoothness assumption is violated. The hypothesis was that Matérn would build a more accurate surrogate. However the result was a regression to 0.442. Matérn may have overfitted to local noise features rather than the underlying structure.",
			},
			{
				w: "W8",
				strategy: "GP-UCB RBF reverted",
				beta: "1.5",
				result: "0.587",
				trend: "new",
				change: "pivot",
				what: "Reverted to the RBF kernel. β=1.5, bias=0.4 kept from the W4/W6 working configuration. All other hyperparameters unchanged.",
				why: "Matern gave a worse result than RBF in W7. This was a clean comparison — the only difference between W6 and W7 was the kernel, and performance declined. Reverting to RBF was unambiguous. The key lesson here: change one thing at a time. Recovery to 0.587 confirmed RBF was the better choice for F2.",
			},
			{
				w: "W9",
				strategy: "GP-UCB keep same",
				beta: "2.0",
				result: "0.567",
				trend: "flat",
				change: "same",
				what: "Settings held at β=2.0, bias=0.4, RBF. No parameter changes.",
				why: "W8 recovered to 0.587 with RBF. Rather than immediately pivoting again, the strategy was held to accumulate another data point in the good region. The result of 0.567 was stable — slightly below 0.587, but well within the noise band of this function. The 0.611 initial best remained unbeaten after 9 weeks.",
			},
			{
				w: "W10",
				strategy: "GP Gradient Ascent",
				beta: null,
				result: "0.055",
				trend: "reg",
				change: "pivot",
				what: "GP Gradient Ascent: the GP surrogate was fitted, then gradient ascent was performed directly on the acquisition function surface — computing ∂(μ + β·σ)/∂x and iteratively stepping toward higher predicted values. This produces a refined candidate rather than the best of N random samples.",
				why: "After 9 weeks stuck below 0.611, random candidate sampling clearly wasn't finding the peak. Gradient ascent was intended to be more precise — directly climbing the GP's predicted surface. However on a noisy multi-modal function, the GP surface has many local maxima, and the gradient led into one that corresponded to a poor region of the true function, returning only 0.055.",
			},
			{
				w: "W11",
				strategy: "GradientBoosting",
				beta: null,
				result: "0.645",
				trend: "new",
				change: "pivot",
				what: "GradientBoosting Regressor (sklearn) used as an alternative surrogate model. Unlike a GP, GradientBoosting uses an ensemble of decision trees fitted with gradient boosting, capturing non-linear patterns and interactions without any smoothness assumptions. The model was fitted on all available (x, y) pairs, then a dense grid of candidates was scored and the predicted maximum selected as the query.",
				why: "Ten weeks without beating 0.611 using GP-UCB warranted a complete surrogate model change. GradientBoosting doesn't rely on a kernel assumption about smoothness, making it potentially better for a noisy, multi-modal landscape. Crucially it found [0.70, 0.85] — a point no GP-UCB random sampling had ever proposed. The result was 0.645: a new all-time best, breaking the 10-week plateau for the first time.",
			},
			{
				w: "W12",
				strategy: "GradientBoosting (continued)",
				beta: null,
				result: "0.6966",
				trend: "new",
				change: "same",
				what: "GradientBoosting continued with the same setup. The model now had one additional data point — the W11 result of 0.645 at [0.70, 0.85] — to learn from, refining its estimate of the optimal region.",
				why: "W11 confirmed GradientBoosting could find regions GP-UCB never reached. With a second consecutive new best (0.6966 at [0.70, 0.70]), the pattern is consistent — the model improves on each iteration as its training set grows. This is the advantage of a data-rich surrogate: each new observation directly shapes the next query.",
			},
		],
	},

	F3: {
		dim: 3,
		desc: "Interior optimum — variance-guided dimension locking from W10 best",
		allBest: { value: "-0.0046", week: "W10" },
		weeks: [
			{
				w: "Initial",
				strategy: "GP-UCB uniform",
				beta: null,
				result: "-0.035",
				trend: "new",
				change: "new",
				what: "Standard GP-UCB on initial data. F3 is 3-dimensional with all-negative outputs — the optimum is the least-negative value achievable.",
				why: "Starting baseline. The negative value suggests an interior optimum exists somewhere in [0,1]³ — this isn't a corner or boundary function. The initial result of -0.035 established the target to beat.",
			},
			{
				w: "W1",
				strategy: "GP-UCB uniform",
				beta: "~2.0",
				result: "-0.150",
				trend: "reg",
				change: "same",
				what: "GP-UCB β≈2.0, uniform random candidates across [0,1]³.",
				why: "The GP moved away from the initial best region, regressing to -0.150. With only ~10 initial data points spread across 3D space, the GP surface is highly uncertain and exploration routinely overrides exploitation. The 3D input space is large enough that random sampling misses the best region frequently.",
			},
			{
				w: "W2",
				strategy: "GP-UCB uniform",
				beta: "~2.0",
				result: "-0.124",
				trend: "new",
				change: "same",
				what: "GP-UCB β≈2.0, same configuration as W1.",
				why: "Slight recovery to -0.124. The GP is slowly triangulating toward the peak based on the growing dataset, but still far from -0.035. No strategic change warranted after only two rounds of improvement.",
			},
			{
				w: "W3",
				strategy: "GP-UCB explore",
				beta: "2.0",
				result: "-0.046",
				trend: "new",
				change: "pivot",
				what: "β confirmed at 2.0 as a deliberate strategy choice, with a focus on broad exploration. The GP-UCB framework with RBF kernel and n_candidates=10,000 was formalised as the standard approach.",
				why: "Recovery to -0.046 was encouraging — closer to -0.035 than any previous week. High β appeared beneficial in 3D space where the optimum region is small relative to total search volume. The GP needed more data near the good region before exploitation would be reliable.",
			},
			{
				w: "W4",
				strategy: "GP-UCB + bias",
				beta: "1.5",
				result: "-0.098",
				trend: "reg",
				change: "pivot",
				what: "β reduced to 1.5 and a bias fraction of 0.5 introduced — half the candidates sampled near the current best point [0.40, 0.41, 0.44] rather than uniformly. The intent was to begin exploiting the region that had shown consistent improvement.",
				why: "W3's -0.046 seemed close enough to the optimum to warrant a shift toward exploitation. However the bias regressed to -0.098. The likely cause: the 3D landscape around the optimum is narrow, and a moderate bias fraction of 0.5 still allowed many candidates in sub-optimal regions, while reduced β caused the algorithm to pick a poor one.",
			},
			{
				w: "W5",
				strategy: "GP-UCB more explore",
				beta: "2.0",
				result: "-0.013",
				trend: "new",
				change: "pivot",
				what: "Reverted to β=2.0 and reduced bias fraction to 0.3 — lighter pull toward best point, primary driver is exploration again. The exploration-exploitation balance tilted back toward exploration.",
				why: "W4's regression confirmed that committing to exploitation too early in a 3D landscape was premature. Lighter bias + higher β was the right balance — the GP explored broadly enough to find a better basin. Result: -0.013, a new all-time best at the time, significantly better than the initial -0.035. The exploration-first philosophy was validated.",
			},
			{
				w: "W6",
				strategy: "GP-UCB exploit best",
				beta: "1.5",
				result: "-0.028",
				trend: "reg",
				change: "pivot",
				what: "With the new best of -0.013 established, β dropped to 1.5 and bias fraction raised to 0.5 to concentrate candidates near [0.40, 0.41, 0.44]. The aim was to refine tightly around the newly-discovered region.",
				why: "Same pattern as W4: finding a new best prompted a move toward exploitation, and the same failure mode: the bias pulled the query slightly off the peak into a slightly worse region (-0.028). F3's optimum occupies a narrow region in 3D space where even small deviations cause notable output drops — exploitation requires higher precision than bias fraction sampling can reliably provide.",
			},
			{
				w: "W7",
				strategy: "GP-UCB + Matern",
				beta: "2.0",
				result: "-0.067",
				trend: "reg",
				change: "pivot",
				what: "Switched to Matérn 5/2 kernel for the GP surrogate, with β=2.0 and bias fraction 0.4. Matérn allows for rougher, less smooth function surfaces compared to RBF.",
				why: "Two consecutive regressions suggested the RBF-based GP wasn't accurately modelling F3. Matérn was trialled as an alternative. The result (-0.067) was worse than W5 and W6. Like F2, Matérn appeared to overfit to local noise in the training data rather than the underlying structure of the function.",
			},
			{
				w: "W8",
				strategy: "GP-UCB exploit RBF",
				beta: "1.0",
				result: "-0.032",
				trend: "new",
				change: "pivot",
				what: "Reverted to RBF kernel. β reduced to 1.0 (heavier exploitation) with bias fraction 0.5. The GP now strongly exploits what it predicts to be the best region.",
				why: "Matérn was clearly worse — reverting to RBF was unambiguous. Dropping β to 1.0 was justified by the accumulated data: by W8, the GP had 8+ queries informing the 3D surface, making the mean prediction more reliable. Recovery to -0.032 validated this, though still just short of the W5 best of -0.013.",
			},
			{
				w: "W9",
				strategy: "GP-UCB keep same",
				beta: "1.0",
				result: "-0.027",
				trend: "new",
				change: "same",
				what: "Held at β=1.0, bias=0.5, RBF. No parameter changes.",
				why: "W8's -0.032 showed the exploitation approach was working. Keeping settings allowed further refinement in the same region. -0.027 improved on W8 — steady convergence toward the -0.013 best. Consistent improvement across W8→W9 justified holding the strategy.",
			},
			{
				w: "W10",
				strategy: "GP Gradient Ascent",
				beta: null,
				result: "-0.0046",
				trend: "new",
				change: "pivot",
				what: "GP Gradient Ascent: the GP surrogate was fitted, then gradient ascent was run starting from the current best point — iteratively computing ∂μ/∂x to step toward the GP's predicted maximum. This produces a candidate at a local maximum of the surrogate surface rather than the best of N randomly-sampled points.",
				why: "Random sampling (even biased) struggles to pin down the exact peak in a narrow 3D optimum region. Gradient ascent directly climbs the surrogate surface, offering more precision than stochastic candidate selection. The result — -0.0046 — was a new all-time best by a large margin, confirming that directed gradient-based search was significantly more effective than random candidates for localising this interior optimum.",
			},
			{
				w: "W11",
				strategy: "GradientBoosting",
				beta: null,
				result: "-0.0116",
				trend: "reg",
				change: "pivot",
				what: "GradientBoosting Regressor used as the surrogate, following its strong performance on F2. The model was fitted on all accumulated (x, y) pairs and its predicted maximum used as the next query.",
				why: "GradientBoosting's success on F2 made it attractive for F3. However it proposed d2=0.75 — well outside the tight cluster where all top results sit (d2≈0.43). The model extrapolated to an untested region, returning -0.0116. The key failure: GradientBoosting has no uncertainty estimate, so it confidently predicted a good region that a GP would have flagged as unexplored and suspicious.",
			},
			{
				w: "W12",
				strategy: "Variance-guided (lock d1)",
				beta: null,
				result: "-0.0222",
				trend: "reg",
				change: "pivot",
				what: "Variance-guided (PCA-inspired) exploration: the top-5 results were analysed to compute the spread of each dimension. d1 had a spread of only 0.066 across the top-5, so it was locked at ≈0.387. Only d2 and d3 (higher variance) were explored.",
				why: "W11's regression showed unconstrained exploration was risky with few rounds left. Locking d1 (the dimension already well-characterised) was intended to reduce the effective search dimensionality from 3D to 2D. However d2/d3 exploration still moved away from the W10 optimal region, returning -0.0222. The W10 gradient ascent result of -0.0046 remains the all-time best.",
			},
		],
	},

	F4: {
		dim: 4,
		desc: "Interior optimum — cluster centre broke through to new W12 best",
		allBest: { value: "0.5621", week: "W12" },
		weeks: [
			{
				w: "Initial",
				strategy: "GP-UCB uniform",
				beta: null,
				result: "-4.03",
				trend: "reg",
				change: "new",
				what: "Standard GP-UCB on initial data. F4 is 4-dimensional. Initial best output was -4.03 — by far the worst starting value across all 8 functions.",
				why: "The deeply negative starting value indicates the initial data landed in a very bad basin of the 4D landscape. The function clearly has positive regions somewhere in [0,1]⁴ given its structure. Immediate exploration to escape this bad basin was the overriding priority.",
			},
			{
				w: "W1",
				strategy: "GP-UCB uniform",
				beta: "~2.0",
				result: "-0.256",
				trend: "new",
				change: "same",
				what: "GP-UCB β≈2.0, uniform candidate sampling across [0,1]⁴.",
				why: "Massive improvement from -4.03 to -0.256 in a single round. The GP's uncertainty-driven exploration jumped out of the initial bad basin into a much more promising region of the 4D space. This confirmed the function has substantial variation and that wide exploration was the right initial approach.",
			},
			{
				w: "W2",
				strategy: "GP-UCB uniform",
				beta: "~2.0",
				result: "-1.221",
				trend: "reg",
				change: "same",
				what: "GP-UCB β≈2.0, uniform sampling. Regressed to -1.221.",
				why: "The W1 jump to -0.256 suggested a better basin existed, but W2 moved away again. With only ~12 data points across a 4D space, the GP surface is still very uncertain. The regression reflected how difficult it is to stay near a good region when exploration pressure dominates and data is sparse.",
			},
			{
				w: "W3",
				strategy: "GP-UCB moderate",
				beta: "1.5",
				result: "-0.847",
				trend: "new",
				change: "pivot",
				what: "β reduced to 1.5 and a weak bias fraction introduced toward the current best point. This shifts the balance slightly from pure exploration toward guided search near known good regions.",
				why: "W2's regression after W1's breakthrough showed the GP was too exploratory — it kept leaving the good region. Dropping β to 1.5 was an attempt to anchor the search closer to -0.256. Recovery to -0.847 (still negative but improved) confirmed that a modest exploitation push helped the GP stay in the right general area of the 4D landscape.",
			},
			{
				w: "W4",
				strategy: "GP-UCB + bias",
				beta: "1.0",
				result: "0.381",
				trend: "new",
				change: "pivot",
				what: "β dropped further to 1.0 (primarily exploitative) with bias fraction 0.4 — 40% of candidates sampled near the current best point. With more data now characterising the 4D landscape, the GP mean prediction was becoming reliable enough to exploit.",
				why: "Three weeks of data had accumulated near the positive-trending region. β=1.0 trusted the GP mean almost exclusively. The result: 0.381 — the first positive value in F4's history. This confirmed that the optimum is positive and located in a specific region of the 4D space. The exploitation strategy at this stage was vindicated.",
			},
			{
				w: "W5",
				strategy: "GP-UCB heavy exploit",
				beta: "0.5",
				result: "0.495",
				trend: "new",
				change: "pivot",
				what: "β dropped to 0.5 — nearly pure exploitation of the GP mean — with bias fraction increased to 0.6. This is the most exploitative setting used so far: 60% of candidates clustered near the current best, and the GP largely ignores uncertainty in favour of its mean prediction.",
				why: "W4's 0.381 was the first positive result and a clear signal that the exploitation strategy was working. Doubling down with β=0.5 was the natural next step. The result: 0.495 — a new best that would stand for 7 weeks. The GP had enough data to make reliable predictions near the optimum basin, and heavy exploitation refined toward it successfully.",
			},
			{
				w: "W6",
				strategy: "Keep same",
				beta: "0.5",
				result: "0.329",
				trend: "reg",
				change: "same",
				what: "Same settings held: β=0.5, bias=0.6, RBF. No changes.",
				why: "W5 gave the best result yet, so no change was made. The regression to 0.329 was attributed to GP noise — the surrogate's mean prediction over a 4D landscape can have small local variations causing the query to land slightly off-peak. One bad sample on a noisy function doesn't invalidate a strategy that just produced the best result.",
			},
			{
				w: "W7",
				strategy: "GP-UCB + Matern",
				beta: "0.75",
				result: "0.269",
				trend: "reg",
				change: "pivot",
				what: "Switched to Matérn 5/2 kernel and raised β slightly to 0.75. Matérn was being tested across multiple functions simultaneously as a systematic kernel comparison experiment.",
				why: "W6's regression prompted investigation of whether a better kernel might produce a more accurate surrogate. However Matérn gave 0.269 — worse than both W5 and W6. For F4, the function appears smooth enough in the optimum region that RBF's smoothness assumption is actually appropriate. Matérn's additional roughness introduced unhelpful variance into the surrogate surface.",
			},
			{
				w: "W8",
				strategy: "GP-UCB RBF reverted",
				beta: "0.5",
				result: "0.444",
				trend: "new",
				change: "pivot",
				what: "Reverted to RBF kernel, β=0.5, bias=0.6 — the W5 settings that produced 0.495.",
				why: "Matérn was clearly worse for F4. Reverting to the W5 winning configuration was unambiguous. Recovery to 0.444 confirmed RBF was the right kernel. This reinforced the principle: don't change the kernel without strong evidence it's better.",
			},
			{
				w: "W9",
				strategy: "Keep same",
				beta: "0.5",
				result: "0.387",
				trend: "reg",
				change: "same",
				what: "Held at β=0.5, bias=0.6, RBF.",
				why: "W8's 0.444 recovery was promising. Holding settings was intended to allow convergence. The slight regression to 0.387 was noise — the GP surrogate in 4D has a complex surface that doesn't converge smoothly. Still in the right ballpark of the 0.495 best.",
			},
			{
				w: "W10",
				strategy: "GP Gradient Ascent",
				beta: null,
				result: "0.386",
				trend: "flat",
				change: "pivot",
				what: "GP Gradient Ascent applied to F4: starting from the best known point, iterative gradient steps taken on the GP's predicted surface across all 4 dimensions.",
				why: "After multiple rounds oscillating near but below 0.495, gradient ascent was tried to achieve the more precise localisation it demonstrated on F3. The result (0.386) was essentially unchanged from W9, suggesting the GP surface near the F4 optimum is very flat — the gradient is nearly zero, meaning there's no useful direction to follow from the current best.",
			},
			{
				w: "W11",
				strategy: "Poly2 surrogate",
				beta: null,
				result: "0.195",
				trend: "reg",
				change: "pivot",
				what: "Polynomial degree-2 (quadratic) regression used as the surrogate model. A second-degree polynomial is fitted to all (x, y) data, producing a smooth quadratic surface across the 4D input space. The analytical maximum of this quadratic surface is found and submitted as the query.",
				why: "On the hypothesis that F4 has a smooth quadratic structure near its peak — which Poly2 would model exactly — this should have predicted the true maximum cleanly. However the proposed query ([0.4, 0.4, 0.4, 0.4]) — the centroid — was far from the known best region, suggesting the quadratic surface was dominated by data points far from the optimum. Regression to 0.195.",
			},
			{
				w: "W12",
				strategy: "Cluster centre",
				beta: null,
				result: "0.5621",
				trend: "new",
				change: "pivot",
				what: "Cluster centre method: the top-5 performing queries (by output value) are identified, and their mean coordinate is computed as the next query. This is entirely non-parametric — no surrogate model is fitted; it simply returns the centroid of the best-known region.",
				why: "Poly2 failed by straying from the proven region. The cluster centre is guaranteed to stay within the convex hull of the best known points — it cannot extrapolate outside what's already been observed to be good. The top-5 queries all clustered near [0.42–0.44, 0.40–0.42, 0.40–0.41, 0.43–0.44], so their centroid [0.423, 0.411, 0.408, 0.434] sat squarely in the best-known basin. Result: 0.5621 — a new all-time best, surpassing W5's 0.495 that had stood for 7 weeks.",
			},
		],
	},

	F5: {
		dim: 4,
		desc: "Corner optimum — [1,1,1,1] confirmed as global maximum in W9",
		allBest: { value: "8662.5", week: "W9" },
		weeks: [
			{
				w: "Initial",
				strategy: "GP-UCB uniform",
				beta: null,
				result: "1088.9",
				trend: "new",
				change: "new",
				what: "Standard GP-UCB on initial data. F5 is 4-dimensional with very large output values (order of thousands). Initial best: 1088.9.",
				why: "The large absolute output values relative to other functions suggested this is a high-gain function. The initial data already contained a value near 1000, suggesting the GP was already in a reasonable region of the space to begin with.",
			},
			{
				w: "W1",
				strategy: "GP-UCB uniform",
				beta: "~2.0",
				result: "179.7",
				trend: "reg",
				change: "same",
				what: "GP-UCB β≈2.0, uniform random candidates.",
				why: "Catastrophic drop from 1088.9 to 179.7. The GP's exploration drove it completely away from the initial good region. In a 4D space with large output gradients, the GP surface is highly uncertain far from observed data, causing exploration to propose points in much worse regions. The initial best was clearly near a specific sub-region that needed to be actively maintained.",
			},
			{
				w: "W2",
				strategy: "GP-UCB uniform",
				beta: "~2.0",
				result: "182.2",
				trend: "flat",
				change: "same",
				what: "GP-UCB β≈2.0, uniform sampling. Result 182.2 — nearly identical to W1.",
				why: "The GP remained stuck in a low-value region. With only ~12 data points across 4D space, the GP's uncertainty was too high everywhere to identify the correct direction back to the 1088.9 basin. Two consecutive near-identical bad results signalled that uniform exploration was completely failing for this function.",
			},
			{
				w: "W3",
				strategy: "GP-UCB biased",
				beta: "0.5",
				result: "1388.9",
				trend: "new",
				change: "pivot",
				what: "The strategy changed to biased sampling: β dropped to 0.5 (heavy exploitation) and the bias fraction was set to sample predominantly near the initial best point. The majority of candidates were generated in a Gaussian neighbourhood around the coordinates from the initial best result, rather than uniformly across [0,1]⁴.",
				why: "W1 and W2 confirmed that uniform exploration was hopeless for rediscovering the initial best basin. By anchoring candidate generation near the coordinates of the initial best, the GP was forced to explore around what was already known to be a good region. The result was 1388.9 — not only recovering but surpassing the initial best by 28%. Biased sampling immediately validated the approach.",
			},
			{
				w: "W4",
				strategy: "GP-UCB heavy exploit",
				beta: "0.5",
				result: "1529.5",
				trend: "new",
				change: "same",
				what: "β=0.5 held, bias fraction increased to 0.7. Even more of the candidates were now generated near the current best point.",
				why: "W3's success validated the bias approach. Increasing the bias fraction to 0.7 concentrated the search further. The GP had now observed three high-value points near the same area of the 4D space, making its mean prediction more reliable there. Result: 1529.5 — another new best.",
			},
			{
				w: "W5–W8",
				strategy: "Keep same",
				beta: "0.5",
				result: "~1400–2235",
				trend: "flat",
				change: "same",
				what: "Settings held at β=0.5, bias=0.7, RBF for four rounds. Results oscillated between ~1400 and ~2235.",
				why: "The strategy was stable and producing values well above the initial baseline. Oscillations were attributed to GP noise in a 4D landscape. Maintaining the same settings allowed the GP to accumulate data in the good region. The trend had stalled, but no single round was bad enough to trigger a strategy change.",
			},
			{
				w: "W9",
				strategy: "Manual probe [1,1,1,1]",
				beta: null,
				result: "8662.5",
				trend: "new",
				change: "pivot",
				what: "A deliberate manual query was submitted: [1, 1, 1, 1] — the corner of the 4D unit hypercube where all dimensions are at their maximum value. This was not proposed by any surrogate model but chosen by direct analysis of the top results.",
				why: "Analysis of the top-5 results showed all dimensions consistently trending toward 1.0 — d1, d2, d3, d4 were all above 0.8 in the best queries. This is the signature of a function where the optimum lies at a boundary corner. For functions with linear or convex-increasing components, the maximum must occur at a vertex of the input domain — a theoretical result, not just a heuristic. Result: 8662.5 — a 5× jump, confirming [1,1,1,1] as the true global maximum.",
			},
			{
				w: "W10",
				strategy: "GP-UCB exploit near corner",
				beta: "0.5",
				result: "7073.4",
				trend: "reg",
				change: "pivot",
				what: "GP-UCB β=0.5 with heavy bias toward [1,1,1,1]. A near-corner probe [1, 0.9, 1, 1] was generated to map the boundary profile and confirm the corner finding.",
				why: "The 5× jump from [1,1,1,1] needed verification: was this a true global maximum or a lucky outlier? Probing [1, 0.9, 1, 1] — varying only d2 — gave 7073.4, clearly below 8662.5. This confirmed d2=1.0 is better than d2=0.9 and that the corner is the optimum. The regression was a deliberate experiment to characterise the boundary slope, not a failure.",
			},
			{
				w: "W11",
				strategy: "Corner probe (inside test)",
				beta: null,
				result: "5439",
				trend: "reg",
				change: "pivot",
				what: "Manual probe at [0.95, 0.95, 0.95, 0.95] — slightly inside all boundaries simultaneously. This tests the gradient from the interior toward the corner.",
				why: "A duplicate query of [1,1,1,1] would waste a round providing no new information. Probing [0.95, 0.95, 0.95, 0.95] confirmed that moving even 5% away from all four boundaries drops the value from 8662.5 to 5439 — consistent with a function that has steep gradients near the corner. Best remains [1,1,1,1].",
			},
			{
				w: "W12",
				strategy: "Near-corner probe",
				beta: null,
				result: "7786.4",
				trend: "reg",
				change: "pivot",
				what: "Manual probe [1, 1, 1, 0.95] — only d4 moved 5% inside the boundary, all others held at 1.0.",
				why: "Extracts the marginal value of d4 at the boundary. Moving only d4 from 1.0 to 0.95 gave 7786.4, down ~876 from the corner. Comparing with W10 (moving d2 from 1.0 to 0.9 cost ~1589), d4 appears to have a slightly smaller gradient near the boundary than d2. These probes collectively build a profile of the boundary surface — confirming [1,1,1,1] as the true global maximum in every dimension.",
			},
		],
	},

	F6: {
		dim: 5,
		desc: "5D interior — variance-guided finally broke 9-week plateau in W12",
		allBest: { value: "-0.2289", week: "W12" },
		weeks: [
			{
				w: "Initial",
				strategy: "GP-UCB uniform",
				beta: null,
				result: "-0.714",
				trend: "reg",
				change: "new",
				what: "Standard GP-UCB on initial data. F6 is 5-dimensional with all-negative outputs — the optimum is the least-negative value achievable.",
				why: "Starting baseline at -0.714. The 5D input space is substantially larger than F1–F4, making random exploration less likely to find the best region quickly. All outputs were negative, consistent with an interior optimum that exists somewhere in [0,1]⁵.",
			},
			{
				w: "W1",
				strategy: "GP-UCB uniform",
				beta: "~2.0",
				result: "-1.288",
				trend: "reg",
				change: "same",
				what: "GP-UCB β≈2.0, uniform random candidates.",
				why: "Regression to -1.288. The GP's exploration in 5D space is even more prone to landing in bad regions than lower-dimensional functions. With uncertainty dominating the acquisition function at this stage, the query was driven to an unexplored area that turned out to be much worse than the starting baseline.",
			},
			{
				w: "W2",
				strategy: "GP-UCB uniform",
				beta: "~2.0",
				result: "-0.733",
				trend: "new",
				change: "same",
				what: "GP-UCB β≈2.0, same configuration. Partial recovery to -0.733.",
				why: "The GP started building a rough picture of the 5D landscape after W1's bad result added a data point in a poor region. Recovery toward -0.714 suggested the GP was orienting back toward the better area. Still far from a clear optimal region.",
			},
			{
				w: "W3",
				strategy: "GP-UCB exploit",
				beta: "1.0",
				result: "-0.258",
				trend: "new",
				change: "pivot",
				what: "β dropped to 1.0 with bias fraction 0.4 — shifting substantially toward exploitation of the GP mean. With 12+ data points accumulated, the GP surface was informative enough to trust for exploitation rather than continued broad exploration.",
				why: "The pattern of W1 regression and W2 partial recovery suggested a clear good basin that exploration kept missing. Dropping β to 1.0 allowed the GP mean to drive the query toward the predicted best region. Result: -0.258 — a dramatic improvement and a new all-time best that would prove incredibly difficult to surpass, standing as the high watermark for 9 weeks.",
			},
			{
				w: "W4–W5",
				strategy: "GP-UCB various",
				beta: "1.0–2.0",
				result: "-0.375 to -1.133",
				trend: "reg",
				change: "pivot",
				what: "Various β and bias fraction combinations tried across two rounds. W5 in particular used bias=0.2 — a very light bias fraction — which produced a catastrophic regression to -1.133.",
				why: "W5's failure with bias=0.2 was instructive: in a 5D space, a light bias fraction of 0.2 allows 80% of candidates to be generated uniformly, which is more than enough for the GP to select a badly-placed query. The lesson: 5D requires either a very tight bias or aggressive exploitation. Light touch doesn't work — the curse of dimensionality means the good basin is a tiny fraction of the total search volume.",
			},
			{
				w: "W6",
				strategy: "GP-UCB bias=0.4",
				beta: "1.0",
				result: "-0.445",
				trend: "new",
				change: "pivot",
				what: "β=1.0, bias fraction raised back to 0.4. The bias fraction increase directly addresses the W5 failure by clustering more candidates near the best known region.",
				why: "W5's -1.133 with bias=0.2 vs W3's -0.258 with bias=0.4 was a clean comparison. In 5D, more bias is needed to keep the search anchored near the good region. Recovery to -0.445 with bias=0.4 confirmed this, though still well short of the -0.258 best.",
			},
			{
				w: "W7",
				strategy: "GP-UCB + Matern",
				beta: "1.0",
				result: "-0.658",
				trend: "reg",
				change: "pivot",
				what: "Matérn 5/2 kernel introduced for the GP surrogate, with bias fraction slightly reduced to 0.3.",
				why: "Following the kernel experiment running across multiple functions, Matérn was tried on F6. The simultaneous reduction in bias fraction (0.4→0.3) compounded the problem — less bias in 5D meant the query drifted further from the good region, and Matérn's rougher surface didn't compensate. Regression to -0.658.",
			},
			{
				w: "W8",
				strategy: "GP-UCB RBF reverted",
				beta: "1.0",
				result: "-0.440",
				trend: "new",
				change: "pivot",
				what: "Reverted to RBF kernel, bias fraction restored to 0.4. All settings returned to the W6 configuration that gave -0.445.",
				why: "Matérn regression was unambiguous — RBF was better for F6. The revert recovered to -0.440, nearly matching W6's -0.445. The consistency of results near -0.44 with these settings suggests this represented a stable exploitative plateau — the GP could reliably find the -0.44 region but couldn't penetrate to -0.258.",
			},
			{
				w: "W9",
				strategy: "Keep same",
				beta: "1.0",
				result: "-0.446",
				trend: "flat",
				change: "same",
				what: "Settings held at β=1.0, bias=0.4, RBF. Result -0.446.",
				why: "Four consecutive rounds near -0.44 indicated GP-UCB had found a local plateau it couldn't escape. The GP's smooth RBF surface apparently had a different local maximum in this region than the true function's -0.258 peak. A new approach was needed.",
			},
			{
				w: "W10",
				strategy: "GP Gradient Ascent",
				beta: null,
				result: "-0.666",
				trend: "reg",
				change: "pivot",
				what: "GP Gradient Ascent: starting from the current best point, gradient ascent was performed on the GP's predicted surface across all 5 input dimensions simultaneously.",
				why: "The -0.44 plateau suggested GP-UCB's random candidate sampling couldn't find the path to -0.258. Gradient ascent was intended to directly climb the surrogate surface. However the gradient pushed strongly toward d3=1.0 and d4=1.0 — wrong corners for F6's interior optimum. The result (-0.666) was worse than the plateau. This revealed that F6's GP surface had a misleading gradient direction near the plateau region.",
			},
			{
				w: "W11",
				strategy: "K-Means cluster",
				beta: null,
				result: "-0.266",
				trend: "new",
				change: "pivot",
				what: "K-Means clustering applied to all accumulated data. The data was partitioned into 3 clusters, each cluster's average output was computed, and the best cluster's centroid was used as the query. This identifies the geographic centre of the region most associated with high outputs across all observed points.",
				why: "Gradient ascent's failure revealed that the GP surface had misleading local gradients. K-Means doesn't follow gradients — it identifies the centre of the best-performing region across all data, which is less susceptible to local surface artefacts. Result: -0.266, nearly matching the W3 best of -0.258 and breaking the -0.44 plateau that had persisted for 4 rounds.",
			},
			{
				w: "W12",
				strategy: "Variance-guided (lock d2/d4)",
				beta: null,
				result: "-0.2289",
				trend: "new",
				change: "pivot",
				what: "Variance-guided exploration: the top-5 results were analysed dimension by dimension. d2 had a spread of only 0.061 across the top-5 (≈0.29 consistently); d4 had a spread of 0.030 (≈0.84 consistently). These were locked. d1 (spread 0.226) and d5 (spread 0.211) were explored freely, while d3 was held at its top-5 mean.",
				why: "K-Means in W11 got within 0.008 of the W3 best. The variance analysis asked: which dimensions are already 'solved' vs which are still causing variance in outputs? d2 and d4 showed near-zero spread in top results — they're at their optimal values. Locking them and exploring only d1 and d5 effectively reduced the problem from 5D to 2D. This precision paid off: -0.2289 beat W3's -0.258, becoming the all-time best after 9 weeks of trying.",
			},
		],
	},

	F7: {
		dim: 6,
		desc: "Interior optimum — Matern + bug fix was the turning point, W12 GP-UCB regressed",
		allBest: { value: "2.066", week: "W10" },
		weeks: [
			{
				w: "Initial",
				strategy: "GP-UCB uniform",
				beta: null,
				result: "1.365",
				trend: "new",
				change: "new",
				what: "Standard GP-UCB on initial data. F7 is 6-dimensional — the highest-dimensional function alongside F8. Initial best: 1.365.",
				why: "A positive initial value of 1.365 in 6D space was a reasonable starting point. However 6D introduces a severe curse of dimensionality: random samples spread extremely sparsely across the 6D unit hypercube, making it very hard to stay near the optimum basin once found.",
			},
			{
				w: "W1",
				strategy: "GP-UCB uniform",
				beta: "~2.0",
				result: "0.017",
				trend: "reg",
				change: "same",
				what: "GP-UCB β≈2.0, uniform random candidates across [0,1]⁶.",
				why: "Catastrophic regression from 1.365 to 0.017. In 6D, the GP's uncertainty is enormous everywhere with only ~12 data points. The acquisition function was dominated by σ terms, driving the query to a completely different unexplored corner of the 6D space that turned out to be near-zero. This illustrated how severe the curse of dimensionality is for random GP-UCB in high dimensions.",
			},
			{
				w: "W2",
				strategy: "GP-UCB uniform",
				beta: "~2.0",
				result: "0.157",
				trend: "new",
				change: "same",
				what: "GP-UCB β≈2.0, uniform sampling. Slow recovery to 0.157.",
				why: "The GP was beginning to learn that some regions are better than others, but with 6D space still highly undersampled, the signal was weak. 0.157 was an improvement but still far from recovering the initial 1.365.",
			},
			{
				w: "W3",
				strategy: "GP-UCB explore",
				beta: "2.0",
				result: "0.354",
				trend: "new",
				change: "pivot",
				what: "β=2.0 confirmed as deliberate policy. Exploration maintained as the primary strategy while data accumulates across the 6D space.",
				why: "Slow but consistent improvement from 0.017 → 0.157 → 0.354 suggested the GP was gradually identifying better regions. In 6D, premature exploitation is very risky — with sparse data, the GP mean is unreliable. Maintaining high β allowed the algorithm to keep building a useful model of the landscape before committing to any sub-region.",
			},
			{
				w: "W4",
				strategy: "NN+GP hybrid",
				beta: null,
				result: "0.080",
				trend: "reg",
				change: "pivot",
				what: "A neural network (small MLP with dropout) was trained on all accumulated data as the surrogate. Gradient ascent was performed on the NN using backpropagation (GradientTape) to find the input maximising predicted output. The NN-proposed candidate was then scored by the GP-UCB acquisition function as a final filter.",
				why: "The course introduced NN+backprop at this stage, and 6D dimensionality made F7 an attractive candidate. The NN was hypothesised to be more expressive than a GP in high dimensions. However the NN's gradient ascent pushed to an extreme boundary point that scored 0.080 — a disaster. The MLP with dropout had only ~15 data points in 6D to learn from, far too few to learn a reliable surface. Gradient ascent with unconstrained clipping led to an extreme, unrepresentative query.",
			},
			{
				w: "W5",
				strategy: "GP-UCB only",
				beta: "2.0",
				result: "0.696",
				trend: "new",
				change: "pivot",
				what: "NN+GP hybrid abandoned entirely. Returned to pure GP-UCB with β=2.0 and bias fraction 0.3 — a light nudge toward the current best while maintaining exploration.",
				why: "The NN disaster in W4 confirmed that neural networks with only ~15 data points in 6D are worse than useless — too little data to learn a reliable 6D surface. GP-UCB, despite its limitations in high dimensions, at least has principled uncertainty estimates. The return to GP-UCB immediately recovered to 0.696 — better than any result since the initial 1.365.",
			},
			{
				w: "W6",
				strategy: "GP-UCB moderate exploit",
				beta: "1.5",
				result: "0.696",
				trend: "flat",
				change: "pivot",
				what: "β reduced to 1.5 and bias fraction raised to 0.4 — shifting slightly toward exploitation of the 0.696 region.",
				why: "With 0.696 established, the temptation was to refine toward 1.365. Dropping β to 1.5 was a mild commitment to that direction. The result was exactly 0.696 again — identical to W5. The strategy wasn't hurting but wasn't helping either. The path back to 1.365 still wasn't clear from the current data.",
			},
			{
				w: "W7",
				strategy: "GP-UCB Matern + bug fix",
				beta: "2.0",
				result: "1.510",
				trend: "new",
				change: "pivot",
				what: "Two simultaneous changes: (1) Matérn 5/2 kernel replacing RBF, and (2) a duplicate-query bug was discovered and fixed. The bug had been causing the algorithm to occasionally re-submit previously-queried points, wasting queries without adding new information. The fix ensured every new query was genuinely novel.",
				why: "The duplicate bug fix alone likely accounted for much of the improvement — wasted queries had been silently degrading the algorithm's effectiveness by adding no new information to the GP's training set. Matérn was also justified: a 6D rough function with an interior optimum is more likely to match Matérn's roughness assumptions than RBF's infinite smoothness. Result: 1.510 — past the initial best for the first time. The bug fix was likely the larger contributing factor.",
			},
			{
				w: "W8",
				strategy: "Keep Matern",
				beta: "2.0",
				result: "1.508",
				trend: "flat",
				change: "same",
				what: "Settings held: β=2.0, Matérn kernel, bias=0.3.",
				why: "W7's breakthrough to 1.510 was too recent to evaluate definitively. W8 returned 1.508 — essentially identical. This confirmed the settings were stable near 1.5 and not a lucky one-off. No change warranted: the strategy had found the right basin.",
			},
			{
				w: "W9",
				strategy: "Keep same",
				beta: "2.0",
				result: "1.782",
				trend: "new",
				change: "same",
				what: "Same settings held. Result: 1.782 — a new best.",
				why: "The GP continued refining its model of the 6D landscape. Correlation analysis of the top results revealed a consistent pattern: d1 and d3 favoured low values (≈0.06–0.14), d6 favoured ≈0.67–0.73. Holding settings allowed the GP to naturally converge toward this optimal region across multiple rounds.",
			},
			{
				w: "W10",
				strategy: "GP Gradient Ascent",
				beta: null,
				result: "2.066",
				trend: "new",
				change: "pivot",
				what: "GP Gradient Ascent applied to F7: starting from the W9 best point [0.136, 0.361, 0.064, 0.227, 0.400, 0.672], iterative gradient ascent was performed on the GP's acquisition surface across all 6 dimensions.",
				why: "Having accumulated 10+ rounds of good data in the right 6D region, the GP mean was now reliable enough to support gradient-based search. The gradient correctly identified that d4 (≈0.22) and d6 (≈0.70) were near their optimal values and should be held, while other dimensions could be refined. Result: 2.066 — a new best, 16% above W9's 1.782. The combination of good data density plus gradient precision was the winning formula.",
			},
			{
				w: "W11",
				strategy: "Cluster centre (KNN)",
				beta: null,
				result: "1.753",
				trend: "reg",
				change: "pivot",
				what: "KNN (K-Nearest Neighbours) used to identify the neighbourhood of the best known point and propose a query based on the centroid of the top-performing nearby points.",
				why: "The KNN query proposed [0, 0, 0.15, 0, 0.6, 0.6] — very different from the W10 best [0.163, 0.361, 0.064, 0.217, 0.325, 0.672]. d2 was set to 0 and d6 to 0.6 rather than the established ≈0.36 and ≈0.67. This moved into a different, worse basin. KNN's neighbourhood calculation in 6D is susceptible to the curse of dimensionality — 'nearest' neighbours in 6D may still be very far from the true optimal region.",
			},
			{
				w: "W12",
				strategy: "GP-UCB β=2.5",
				beta: "2.5",
				result: "1.1628",
				trend: "reg",
				change: "pivot",
				what: "Returned to GP-UCB with β=2.5 — moderately aggressive exploration. The high β was intended to escape the KNN regression and explore broadly enough to find the region a classmate had found (benchmark: 2.71).",
				why: "With two regressions from the W10 best of 2.066, aggressive exploration seemed necessary. However β=2.5 produced a query at [0.774, 0.439, 0.859, 0.697, 0.094, 0.976] — almost all high values — the opposite of the established pattern (low d1, low d3, d6≈0.70). In 6D, the GP's uncertainty is very high in unexplored high-value regions, and β=2.5 chased that uncertainty into a completely wrong area of the space. Worst result since W6.",
			},
		],
	},

	F8: {
		dim: 8,
		desc: "Near-linear function — boundary optimum, W12 new best via variance-guided",
		allBest: { value: "9.9649", week: "W12" },
		weeks: [
			{
				w: "W1",
				strategy: "GP-UCB uniform",
				beta: "~2.0",
				result: "9.943",
				trend: "new",
				change: "new",
				what: "Standard GP-UCB uniform exploration across [0,1]⁸. The first query happened to land at [0.062, 0.097, 0.101, 0.089, 0.998, 0.369, 0.144, 0.738], giving 9.943.",
				why: "Completely serendipitous — the first GP-UCB query in an 8D space happened to find a near-optimal point. The coordinate pattern was revealing: d1–d4 and d7 all very low (≈0.06–0.14), d5 near 1.0 (0.998), d8 moderate (0.738). This suggests a near-linear function where the optimum sits at the boundary defined by minimising d1–d4/d7 and maximising d5. The challenge for subsequent rounds was to match or surpass this lucky first shot.",
			},
			{
				w: "W2",
				strategy: "GP-UCB uniform",
				beta: "~2.0",
				result: "9.810",
				trend: "reg",
				change: "same",
				what: "GP-UCB β≈2.0, uniform sampling. Slight regression to 9.810.",
				why: "With only W1's result as a data point near the good region, the GP's uncertainty everywhere else was high. The query moved away from the W1 boundary pattern into a slightly more interior region. This confirmed that F8's optimum is at a specific boundary of the 8D space — not an interior point — and that the GP needed more data near that boundary to stay anchored there.",
			},
			{
				w: "W3–W4",
				strategy: "GP-UCB moderate",
				beta: "1.5–2.0",
				result: "9.849–9.910",
				trend: "new",
				change: "same",
				what: "β varied between 1.5 and 2.0 across two rounds. Results gradually improved, approaching but not exceeding W1's 9.943.",
				why: "The GP was accumulating data near the W1 boundary pattern, allowing its surface to better characterise the optimal region. Gradual improvement confirmed the GP was orienting correctly. W1's best remained out of reach because the GP's uncertainty-driven sampling kept placing queries slightly off the precise boundary coordinates — exactly the problem that a directed approach would later solve.",
			},
			{
				w: "W5",
				strategy: "NN+GP hybrid (conservative)",
				beta: "1.5",
				result: "9.899",
				trend: "new",
				change: "pivot",
				what: "Neural network surrogate introduced for F8 — the highest-dimensional function (8D). A small MLP with dropout was trained on accumulated data, then gradient ascent via backpropagation was performed starting from the current best point. Conservative settings were used: gradient_lr=0.005 (small steps), n_gradient_steps=50, outputs clipped to [0.05, 0.95] rather than [0, 1].",
				why: "The course introduced NN+backprop at this stage, and F8's 8D dimensionality made it the most appropriate candidate — higher dimensions theoretically benefit most from gradient-based search. Conservative settings (low learning rate, clipping to [0.05, 0.95] rather than [0, 1]) were intended to prevent the NN from aggressively pushing to extreme boundary values before the pattern was fully confirmed. Result: 9.899 — stable but not a new best.",
			},
			{
				w: "W6",
				strategy: "NN+GP hybrid",
				beta: "1.5",
				result: "9.857",
				trend: "reg",
				change: "same",
				what: "Same NN+GP settings. Slight regression to 9.857.",
				why: "The NN gradient proposed a candidate slightly off the optimal boundary pattern — d5 landed below 0.95 and d1–d4 not quite at their minimum values. The clipping to [0.05, 0.95] was actively preventing the gradient from reaching the true boundary values (d5 should ideally be ≈1.0, not capped at 0.95), which may have limited performance.",
			},
			{
				w: "W7",
				strategy: "NN+GP + more random",
				beta: "1.5",
				result: "9.660",
				trend: "reg",
				change: "pivot",
				what: "n_random (the number of random candidates evaluated alongside the NN gradient candidate) was increased from 1000 to 2000, hoping that a larger random pool would help identify better candidates across the 8D space.",
				why: "The hypothesis was that more random candidates would improve odds of finding a better point. In practice, doubling the random pool spread the search wider across the 8D space, away from the tight boundary cluster that characterises the optimum. With 2000 random candidates across [0,1]⁸, the algorithm sampled much more of the non-optimal interior, and the acquisition function naturally favoured some of these highly-uncertain interior points. Regression to 9.660.",
			},
			{
				w: "W8",
				strategy: "NN+GP reverted",
				beta: "1.5",
				result: "9.898",
				trend: "new",
				change: "pivot",
				what: "n_random reverted to 1000. All other settings unchanged.",
				why: "The W7 experiment confirmed that wider random sampling hurts in 8D. Recovery to 9.898 with n_random=1000 demonstrated a key principle: in 8D, quality of candidates near the boundary matters more than quantity spread across the whole space. Fewer well-placed candidates outperforms many candidates spread uniformly.",
			},
			{
				w: "W9",
				strategy: "NN+GP keep same",
				beta: "1.5",
				result: "9.903",
				trend: "new",
				change: "same",
				what: "Settings held at n_random=1000, gradient_lr=0.005. Incremental improvement to 9.903.",
				why: "Steady progress toward the 9.943 W1 best. The NN+GP hybrid was consistently producing results in the 9.89–9.91 range, slowly converging. No reason to change a stable, improving strategy — each round added more data near the boundary pattern, improving the NN's accuracy.",
			},
			{
				w: "W10",
				strategy: "GP Gradient + NN",
				beta: null,
				result: "9.884",
				trend: "reg",
				change: "pivot",
				what: "GP-based gradient ascent combined with NN candidates. Starting from the W1 best point, gradient ascent was applied directly to the GP acquisition surface in all 8 dimensions simultaneously.",
				why: "Applied across multiple functions simultaneously in this round. On F8, the gradient slightly overshot the optimal boundary point — d5 was pushed too high while d1–d4 moved away from their near-zero optimal values. The result (9.884) was slightly worse than W9's 9.903. The GP gradient in 8D is sensitive to the kernel's estimated surface, which may not perfectly capture the near-linear boundary structure.",
			},
			{
				w: "W11",
				strategy: "Cluster centre",
				beta: null,
				result: "9.953",
				trend: "new",
				change: "pivot",
				what: "Cluster centre of the top-5 results: the mean coordinate of the five highest-valued queries was computed and submitted as the next query. No surrogate model fitted — purely the geographic centroid of the best-known region.",
				why: "By W11, the top-5 results all shared a clear pattern: d1≈0.06, d4≈0.08, d5≈0.96, d7≈0.14, d8≈0.70. The cluster centre naturally gravitated to this pattern without any model fitting or gradient calculation. Result: 9.953 — a new all-time best, surpassing W1's 9.943 for the first time in 10 rounds. The simplest method turned out to be the most effective at this stage.",
			},
			{
				w: "W12",
				strategy: "Variance-guided (lock d1/d4/d5)",
				beta: null,
				result: "9.9649",
				trend: "new",
				change: "pivot",
				what: "Variance-guided (PCA-inspired) exploration: the top-5 results were analysed dimension by dimension. d1 (spread 0.038), d4 (spread 0.057), and d5 (spread 0.051) all showed very low variance — consistently at their near-boundary values. These were locked. d2 (spread 0.323), d6 (spread 0.287), and d7 (spread 0.172) showed high variance and were explored freely. d3 and d8 were held at their top-5 means.",
				why: "The cluster centre in W11 confirmed the boundary pattern for d1/d4/d5. But could we do better by only exploring the truly uncertain dimensions? Locking d1/d4/d5 and exploring only d2/d6/d7 effectively reduced the problem from 8D to 3D — a much more tractable search. Result: 9.9649 — another new best, confirming that systematic dimension locking is more effective than re-optimising all 8 dimensions simultaneously when most are already well-characterised.",
			},
			{
				w: "W13",
				strategy: "Variance-guided (lock d1/d4/d5)",
				beta: null,
				result: "9.9680",
				trend: "new",
				change: "same",
				what: "Variance-guided continued with d1/d4/d5 locked. Query [0.060, 0.182, 0.089, 0.076, 0.959, 0.469, 0.163, 0.692] — d2/d6/d7 explored at slightly different values to W12.",
				why: "W12 proved the dimension-locking approach worked for F8. W13 continued exploring d2, d6, and d7 with the boundary pattern anchored. Result: 9.9680 — a third consecutive new best (W11: 9.953, W12: 9.965, W13: 9.968). The method's success across three rounds confirmed that the 8D problem had been effectively reduced to a 3D search over the uncertain dimensions.",
			},
		],
	},
};
